#!/usr/bin/env bash
set -euo pipefail

SSH_BIN="${ORACLE_TUNNEL_SSH_BIN:-ssh}"
ORACLE_TUNNEL_HOST="${ORACLE_TUNNEL_HOST:-}"
ORACLE_TUNNEL_USER="${ORACLE_TUNNEL_USER:-}"
ORACLE_TUNNEL_KEY_PATH="${ORACLE_TUNNEL_KEY_PATH:-}"
ORACLE_TUNNEL_REMOTE_BIND_ADDRESS="${ORACLE_TUNNEL_REMOTE_BIND_ADDRESS:-127.0.0.1}"
ORACLE_TUNNEL_REMOTE_PORT="${ORACLE_TUNNEL_REMOTE_PORT:-3302}"
ORACLE_TUNNEL_LOCAL_HOST="${ORACLE_TUNNEL_LOCAL_HOST:-127.0.0.1}"
ORACLE_TUNNEL_LOCAL_PORT="${ORACLE_TUNNEL_LOCAL_PORT:-3102}"
ORACLE_TUNNEL_SERVER_ALIVE_INTERVAL="${ORACLE_TUNNEL_SERVER_ALIVE_INTERVAL:-30}"
ORACLE_TUNNEL_SERVER_ALIVE_COUNT_MAX="${ORACLE_TUNNEL_SERVER_ALIVE_COUNT_MAX:-3}"
ORACLE_TUNNEL_STRICT_HOST_KEY_CHECKING="${ORACLE_TUNNEL_STRICT_HOST_KEY_CHECKING:-accept-new}"

if [[ -z "${ORACLE_TUNNEL_HOST}" ]]; then
    echo "Missing ORACLE_TUNNEL_HOST" >&2
    exit 1
fi

if [[ -z "${ORACLE_TUNNEL_USER}" ]]; then
    echo "Missing ORACLE_TUNNEL_USER" >&2
    exit 1
fi

if ! command -v "${SSH_BIN}" >/dev/null 2>&1; then
    echo "Missing SSH binary: ${SSH_BIN}" >&2
    exit 1
fi

if [[ -n "${ORACLE_TUNNEL_KEY_PATH}" && ! -f "${ORACLE_TUNNEL_KEY_PATH}" ]]; then
    echo "SSH key not found: ${ORACLE_TUNNEL_KEY_PATH}" >&2
    exit 1
fi

SSH_OPTS=(
    -N
    -T
    -o ExitOnForwardFailure=yes
    -o ServerAliveInterval="${ORACLE_TUNNEL_SERVER_ALIVE_INTERVAL}"
    -o ServerAliveCountMax="${ORACLE_TUNNEL_SERVER_ALIVE_COUNT_MAX}"
    -o StrictHostKeyChecking="${ORACLE_TUNNEL_STRICT_HOST_KEY_CHECKING}"
)

if [[ -n "${ORACLE_TUNNEL_KEY_PATH}" ]]; then
    SSH_OPTS+=(-i "${ORACLE_TUNNEL_KEY_PATH}")
fi

REMOTE_SPEC="${ORACLE_TUNNEL_REMOTE_BIND_ADDRESS}:${ORACLE_TUNNEL_REMOTE_PORT}:${ORACLE_TUNNEL_LOCAL_HOST}:${ORACLE_TUNNEL_LOCAL_PORT}"
TARGET="${ORACLE_TUNNEL_USER}@${ORACLE_TUNNEL_HOST}"

exec "${SSH_BIN}" "${SSH_OPTS[@]}" -R "${REMOTE_SPEC}" "${TARGET}"
